export const ENDPOINTS = {
  createBooking: "/booking",
  sendOtp: "/booking/send-otp",
  verifyOtp: "/booking/verify-otp",
  bookingList: "/bookings",
  bookingDetails: (id: number | string) => `/bookings/${id}`,
  cancelBooking: (id: number | string) => `/bookings/${id}/cancel`,
  rescheduleBooking: (id: number | string) => `/bookings/${id}/reschedule`,
  restaurantSignup: "/restaurant/signup",
  restaurantLogin: "/restaurant/login",
  superAdminLogin: "/superadmin/login",
  restaurantDashboard: "/restaurant/dashboard",
  bookingSlots: "/restaurant/booking-slots",
  superAdminDashboard: "/superadmin/dashboard",
  bookingSlotStatus: "/admin/booking-slots/status",
  bookingStatus: "/admin/bookings/status",
  contactSendEmail: "/contact/send-email",
} as const;
